### ISSUE TITLE
Cross-Session Persistence of User Settings

### ISSUE THREAD

**Issue by Richard-Walter** [Christian1984/vfrmap-for-vr#10]
Small issue but would be nice to save map settings.  Everytime I run your the app I have to toggle off navigational data

**Comment by Christian1984** [comment]
I see what you mean. Up to this point, I have only implement client-side **session-persistence**, i.e. you have to configure these things once per flight, and then it stays this way for this particular flight. This should already be working properly in 1.1.0. Do you encounter issues with this "session persistence"? Or are you requesting persistence across multiple flights?

**Comment by Richard-Walter** [comment]
Yeah...I'm requesting persistence across multiple flights?

**Comment by Christian1984** [comment]
This will be fixed with upcoming v1.6!
