### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by heerzJon-E** [Christian1984/vfrmap-for-vr#11]
Hello, Christian.

Great work on FSKneeboard! I cannot find a way to toggle a dark mode for night/storm flying. The display is fine during the day but too bright when it's dark out.

Thank you.

**Comment by Christian1984** [comment]
For the time being, you can select the "Carto Dark" map, but I do understand that you would like to see a dark mode for the charts viewer and notepad, preferably the entire panel, as well! Thanks for the suggestion!

**Comment by Christian1984** [comment]
done! I implemented a brightness control which you can use to set the overall panel brightness in 10% increments as well as a "red flash light mode"!

![dark-mode-4](https://user-images.githubusercontent.com/5574632/121498897-2aec0b80-c9dd-11eb-9fdc-30c69b45346e.png)
![dark-mode-3](https://user-images.githubusercontent.com/5574632/121498901-2c1d3880-c9dd-11eb-8d4b-65811b38f80b.png)
![dark-mode-2](https://user-images.githubusercontent.com/5574632/121498903-2cb5cf00-c9dd-11eb-9d3c-70693fdca08b.png)
![dark-mode-1](https://user-images.githubusercontent.com/5574632/121498906-2cb5cf00-c9dd-11eb-918c-4c79027dde0a.png)
