### ISSUE TITLE
Hotkey to show/hide FSKneeboard

### ISSUE THREAD

**Issue by heerzJon-E** [Christian1984/vfrmap-for-vr#12]
Is there a way to setup a key or button binding to toggle the FSKneepad display. I have a button mapped to toggle the default MSFS VFR map, which is very handy in VR, and I would like to be able to do the same for this.

Thank you.

**Comment by Christian1984** [comment]
Thanks a bunch for the great suggestion.

In fact, you aren't the first to bring this up (but the first one publicly posting this as an issue, so thanks a lot!) and it's definitely on my roadmap.

I'll leave the issue open to avoid duplicates until it is implemented, if feasible!

**Comment by Christian1984** [comment]
done and implemented as experimental feature. please provide feedback when released!
