### ISSUE TITLE
Load Flight Plan From MSFS Into FSKneeboard

### ISSUE THREAD

**Issue by Richard-Walter** [Christian1984/vfrmap-for-vr#14]
It would be nice to add flight plan to charts viewer,

**Comment by Christian1984** [comment]
Hi Richard-Walter. Can you elaborate a bit what you mean.

Like what kind of flight plan? Do you mean a table where you have courses, distances, ETAs etc. listed? One way to do it right now would be to create a table with excel or a similar tool like a dedicated flight planner, export is as png or screenshot it and add it to your charts folder. Can you please point out what it is exactly that you would like to see added? :-)

Or do you mean automatically adding waypoints from your in-game-flightplan to the map?

**Comment by Richard-Walter** [comment]
Just like you can load the flighplan in little nav map and see the plan follow the flight plan path.  Just a line between waypoint segments

**Comment by Christian1984** [comment]
So what you can currently do on the map viewer is add manual waypoints and then watch your moving airplane following it. What I am currently implementing in addition to that is the possibility to pull the flightplan from msfs onto the map with a click of a button. That is what you are asking for, am I right?

**Comment by Richard-Walter** [comment]
Yep...pull the flight plan from msfs is a good idea

**Comment by Christian1984** [comment]
Great! Then this is almost done :-)

**Comment by Christian1984** [comment]
done!
