### ISSUE TITLE
Option for window close on MSFS exit

### ISSUE THREAD

**Issue by smitty97** [Christian1984/vfrmap-for-vr#16]
I launch MSFS + FSkneeboard with Addons Linker.  
If the fskneeboard server window is still up from a previous session with "Press enter to exit" then it will not relaunch a new server.

Please add a launch option --cleanexit or something that simply closes the server window on MSFS exit.  No is need to press enter.

**Comment by Christian1984** [comment]
Sounds good!

**Comment by Christian1984** [comment]
done! Thanks for the suggestion @smitty97 - Will be released with v1.3.0 soon...
