### ISSUE TITLE
Add Wind Information

### ISSUE THREAD

**Issue by aduboy** [Christian1984/vfrmap-for-vr#17]
Hello,

Thank you very much for your work om this excellent application. It is really great for flying in VR!

As an additional feature in the future, would it be possible to display wind speed and wind direction over the map?
For example, the old application Vfrma-enhanced had this type of information displayes in a bar at the top of the window (see screenshot attached) and it was very useful when landing at uncontrolled airports without ATIS.
![VFRMAP Enhanced](https://user-images.githubusercontent.com/45800037/120033277-a91eda00-bffb-11eb-9cbe-93e2c6a1477e.JPG)

Thank you very much and greetings from Spain!

**Comment by Christian1984** [comment]
HEy @aduboy - Thanks for the suggestion. Yes, that is something I already put on my TODO-List recently! :-) I'll leave the issue open until I have implemented it to avoid duplicates!

**Comment by Christian1984** [comment]
done!

![fskneeboard-wnd-1](https://user-images.githubusercontent.com/5574632/120918402-9881fa00-c6b4-11eb-8072-2b221a5ac67e.PNG)
