### ISSUE TITLE
Change Fontsizes to standart after minimize and than maximize

### ISSUE THREAD

**Issue by FenEstron135** [Christian1984/vfrmap-for-vr#20]
Hi, 
when i optimize the fontsize with the arrows ooinside the kneeboard and i minimize and than i maximize it again, all letzers on standard size and i have tobresize it again.
After the maximizing the kneeboard is new connecting to the server, i think.

**Comment by Christian1984** [comment]
Thanks for letting me know! I'll look into it!

**Comment by Christian1984** [comment]
done! fix will be part of 1.4.0
