### ISSUE TITLE
magenta line drawn from aircraft to first waypoint

### ISSUE THREAD

**Issue by Richard-Walter** [Christian1984/vfrmap-for-vr#21]
After loading the flight plan, a magenta line is always drawn from the aricraft to the first waypoint as shown in the attached photo.  Shouldn't it behave just like a normal garmin GPS?  HOw do we get rid of the magenta line attached to the aircraft?

![Capture](https://user-images.githubusercontent.com/47770368/121775514-87ad1900-cbcb-11eb-851c-73f7ade4e0fe.PNG)

**Comment by Christian1984** [comment]
Hi Richard.

My suggestion would be to simply remove that very first waypoint (which you have already passed, if I understand the situation shown in the image correctly?).

In my opinion, the system behaves as it is supposed to: The "first" waypoint is always the "next" waypoint and a magenta line is drawn from your current position to that ofrst waypoint (or, if you hide the aircraft symbol from your last "known" position).

Does this do the trick? Or what is the exact behaviour that you would expect?

Chris

**Comment by Richard-Walter** [comment]
Hey Chris, I guess I was after behaviour that is similar to Little Nav Map
and real world GPS avionics.  Only the flight plan is shown... there is no
connection between the aircraft and a waypoint.  I've attached a photo from
'little nav map' as an example.  My plane is off track represented by the
yellow plane icon.  Note there is no line drawn from the plane to the next
waypoint.  Hope this clears things up.

RIchard

**Comment by Christian1984** [comment]
I have changed the behaviour in case the airplane is NOT visible: In that scenario the first line from the ltest known aircraft position to the first waypoint will be hidden... Otherwise a magenta line will be drawn from your current position to the first waypoint (as was before).

Will be released with v1.4
