### ISSUE TITLE
New feature - hotkey (problem with "Alt+...") is a problem

### ISSUE THREAD

**Issue by yoyo251** [Christian1984/vfrmap-for-vr#23]
Hi,
please to add more hotkeys, with Alt is unused for me. I use many save view position (so with Alt+1, 2 ect) but when I hit Alt in MSFS in VR I change position (to default one) and open in the same time FSKneeboard. Also I I jump to external view and back to VC (so with Alt also) FSKneeboard opens too immediately. With Alt+ T I see big blue circle on the ground so this key is wrong. Please to add something more with Shift or Ctrl. Thank You!

**Comment by yoyo251** [comment]
Also exist problem when you back from pan or drone view to VC, in the same time FSKneeboard opens too.

**Comment by Christian1984** [comment]
I have added

- [Ctrl]+[Shift]+F
- [Ctrl]+[Shift]+K
- [Ctrl]+[Shift]+T

as additional options!

Will be released with v1.4

**Comment by yoyo251** [comment]
Thank You :- )))) ! btw. if you want I can check it before release :).   Rafal. 
            
          
     
      
       
        Dnia 20 lipca 2021 10:38 Chris ***@***.***&gt; napisał(a):
       
    
       
         
 I have added 
 
 [Ctrl]+[Shift]+F 
 [Ctrl]+[Shift]+K 
 [Ctrl]+[Shift]+T 
 
 as additional options! 
 Will be released with v1.4
