### ISSUE TITLE
MSFS Jul 27 update/Detached map freezes and causes MSFS to crash

### ISSUE THREAD

**Issue by nikolaygekht** [Christian1984/vfrmap-for-vr#24]
Environment:
MSFS with July 27 update
Win 10
Paid version of VFR Map

1) When I detach the map and move it to another display it completely freezes. 
NOTE: pre-July 27 update, it was just lagging, but now it completely freezes

2) No matter how it is opened, detached, or not it now causes MSFS crash. I used it pre-update for a few days and there were no crashes. 

Yep, I checked, if I remove `christian1984-ingamepanel-fskneeboard` from the RoaminPackages/Community MSFS works perfectly. 

If more details are needed or any debug version need to be tried in my config, please feel free to get in touch with me.

**Comment by Christian1984** [comment]
As a workaround for the time being I would suggest to NOT use detached mode for now, but rather open a regular browser on your second screen and load up localhost:9000 until the issue has been sorted...

**Comment by Christian1984** [comment]
Is this issue still a thing, @nikolaygekht ? Or was it fixed by a sim update in the meantime?

**Comment by Christian1984** [comment]
This issue hasn't received any feedback from the reporter sind september. I'll close it for now. If the issue persists/reappears, please comment and reopen it.
