### ISSUE TITLE
Support for using the browser view on external devices (second PC, mobile)

### ISSUE THREAD

**Issue by RaffCode-Personal** [Christian1984/vfrmap-for-vr#26]
So, I just found your other post about using the viewer in the browser via localhost:9000 (btw, the ingame client doesn't seem to cause CTD for me this far) which works perfectly. I would like to use that on my Android tablet though so I tried it by replacing localhost with my PC's local IP address, but that only gave me the top bar of the map with missing symbols while the map body showed an error because the html seems to be hardcoded to look for localhost.

An option to use this via a browser on other devices would be killer for everybody not playing in VR (I think I prefer to play on my screen in HDR until faster GPUs are out that allow better performance / image quality on my Index). At least for Android there doesn't seem to be much available that allows to import a MSFS2020 flight plan let alone has a highly detailed map and the option to toggle GPS off.

**Comment by Christian1984** [comment]
Interesting thought! I'll definitely look into that!!! And good analysis by the way: The hardcoded localhost as src attributes on the iframes is exactly why it fails!

**Comment by RaffCode-Personal** [comment]
Thanks for the reply. While I would be totally cool with just some hacky solution to use the web browser of an external device, depending on how serious you take this app it might be a sensible idea to hack together a quick and dirty web app for Android and iOS. That way you could basically advertise your app on the mobile app stores as well. Just as an idea :-)

**Comment by BigAlsFlying** [comment]
Hi @Christian1984  wonderful app love using it make getting around in VR a lot easier . Agree with @xxTheGoDxx xxTheGoDxx  if it was able to be opened in external web browser using the ip-address:9000 that would be great. Also I'm sure for a while when I was running the free version that was the case as I was able to run MSFS2020 on on my gaming pc  &  access FSKNEEBOARD on my other pc using ip-adddress:9000 but that just stopped working . 

 Like @xxTheGoDxx i get the screen up but no data on it .  Also not sure if it was possible to get it to working  in X-Plane as well . Would open  up a whole new market for you as a lot  of us use X-Plane VR  as well as MSFS2020 .  

Keep up the great work . 

Al

**Comment by Christian1984** [comment]
This will be fixed in upcoming v1.6 :+1:
