### ISSUE TITLE
distance and heading wrong after importation in FSKNEEBOARD

### ISSUE THREAD

**Issue by Mutekidav** [Christian1984/vfrmap-for-vr#31]
Hello,
When I make my flight plan in mfs and import it in FSKNEEBOARD, the distance and the heading are wrong...
The navigation log in MFS shows the correct data.
There is a 13% error.
Am I doing something wrong? 
Thanks for your help!

**Comment by Christian1984** [comment]
Thanks for the report! Can you please provide an example flight plan/waypoints, preferably with ICAO codes to recreate and a few screenshots?

**Comment by Mutekidav** [comment]
I'am so sorry Chris,
when I tried to make screenshots, I realized that the units of measurement are in miles and not in nautical miles.
And MFS is in NM and not in Mi like your software.

Do you think you can find a solution to choose the unit of measurement please?

**Comment by Christian1984** [comment]
Sorry for the late response. I'll have to double check that. Obviously, it should be in NM... I'll take a look!

**Comment by Christian1984** [comment]
Calculation of NM is fixed and will be released with the upcoming v1.6 update!
