### ISSUE TITLE
Save independent zoom/pan for each chart

### ISSUE THREAD

**Issue by imjinc2k** [Christian1984/vfrmap-for-vr#32]
Flipping between a 4000x4000 VFR chart and a 1000x1000 airport diagram has the user manually panning and zooming each time, since those values seem to be global.  This would be more useful if each chart preserved its own independent zoom and pan settings during a session, so that when you flip back to a chart it shows the same area you left it on, regardless of how you've zoomed/panned other charts.

**Comment by Christian1984** [comment]
Good thinking. I'll take it into consideration!

**Comment by Christian1984** [comment]
done! to be released with v1.9
