### ISSUE TITLE
Program remaining open after shutting down the sim and more

### ISSUE THREAD

**Issue by Strat919** [Christian1984/vfrmap-for-vr#34]
Hey Christian. Thanks for creating this great app:) I have a question. Is there any reason why you have the program remaining open  after  MSFS has been shut down? Is it possible to have it close automatically instead of having to hit enter? Maybe there is a reason I don't see. I run a batch opening fsdevmodelauncher.exe and vfr-for-vr instead of your fskneeboard-autostart-windows-store.bat. It saves about a minute in initial sim loading time. No big deal but thought I'd bring it up:)

Also, would it be possible for the map to retain it's zoom?

One more thing that is probably not possible and most likely very hard.  The teleport function works great when you perform it in the air, but when you do it while on the ground.... it doesn't work very well. Is there any way for it to know the exact elevation to where it teleports to?

Thanks:)

**Comment by Christian1984** [comment]
Hi Strat919 and sorry for the late reply. See comments inline below:

> Is there any reason why you have the program remaining open after MSFS has been shut down? Is it possible to have it close automatically instead of having to hit enter? Maybe there is a reason I don't see. I run a batch opening fsdevmodelauncher.exe and vfr-for-vr instead of your fskneeboard-autostart-windows-store.bat. It saves about a minute in initial sim loading time. No big deal but thought I'd bring it up:)

Yes, totally possible. Please run `fskneeboard.exe --quietshutdown` as described in the docs here: https://github.com/Christian1984/vfrmap-for-vr#advanced-usage - That should solve your issue :-)

> Also, would it be possible for the map to retain it's zoom?

Yes, that will be released with upcoming v1.6 - The maps zoom will not be persisted, but the resolution scaling is, hence it doesn't have to be reset with every flight :-) I assume that this is what you are after, huh?

> One more thing that is probably not possible and most likely very hard. The teleport function works great when you perform it in the air, but when you do it while on the ground.... it doesn't work very well. Is there any way for it to know the exact elevation to where it teleports to?

One option would be to query the google maps or open street map API or so and request the ground level altitude for the position the marker was placed; but personally I don't see a benefit that justifies the work that I would have to put into this feature. If this feature request gets some traction and "public demand", though, I'm happy to revisit it! Or maybe someone else would like to work on it. After all, the teleport feature is entirely part of the free version and thus open source!

> Thanks:)

I'd like to close the issue for now. If you have further requests, please feel free to comment and reopen it, or visit us at https://discord.fskneeboard.com to discuss this more "casually" :-)
