### ISSUE TITLE
Request: Improvements to charts viewer

### ISSUE THREAD

**Issue by BjornB2** [Christian1984/vfrmap-for-vr#35]
Hi! Just installed the free version and would like to upgrade to pro, but I think the charts viewer would be more helpful with some features added:

1. A pdf to png conversion script
2. Multi page PDF (I.E. a checklist) to multiple PNG's with possibility to view them as a single document in the viewer
<s>3. Folder structure for png's</s> Seems to be there already :)

1 and 2 are actually features I found in the [ebag mod](https://nl.flightsim.to/file/9001/ebag-electronic-flight-bag-also-works-in-vr) I found on flightsim.to. For myself I already modified the conversion script to output PNG's in stead of JPG's. 

Hope you can add these features :)

Thanks
Björn

P.S. code to convert to png in the existing folder structure of the ebag mod:

cd code
for %%f in (..\ebag\*.pdf) do (
	.\gswin64c.exe -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=png16m" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r150x150" -o "..\ebag\%%~nf---%%03d.png" "%%f"
)

**Comment by BjornB2** [comment]
[fskneeboard-charts.zip](https://github.com/Christian1984/vfrmap-for-vr/files/7610209/fskneeboard-charts.zip)


Made a sample where the pdfs in the pdf folder are processed and placed in \processed\originalfilename\ subfolders. Hope this somehow helps.

**Comment by BjornB2** [comment]
[fskneeboard-charts-subdirs.zip](https://github.com/Christian1984/vfrmap-for-vr/files/7611536/fskneeboard-charts-subdirs.zip)

Made some changes now I have the PRO license:

Put files in the pdf folder in subfolders and optional also in sub-sub folders. Folder structure and converted files will be put in C:\fskneeboard-server\charts\
Change the .bat to suit your needs.

To do: Add if not exist to pdf files before converting.

example:

Input
pdf\Charts\EHHV\chart1.pdf
pdf\Charts\EHHV\chart2.pdf
pdf\Checklists\Piper P28R\Checklist.pdf

Output:"
C:\fskneeboard-server\charts\Charts\EHHV\chart1.png
C:\fskneeboard-server\charts\Charts\EHHV\chart2.png
C:\fskneeboard-server\charts\Checklists\Piper P28R\Checklist---001.png
C:\fskneeboard-server\charts\Checklists\Piper P28R\Checklist---002.png
C:\fskneeboard-server\charts\Checklists\Piper P28R\Checklist---003.png

**Comment by OverWorldD** [comment]
Where do I set the server directory for charts?

**Comment by BjornB2** [comment]
You would have to edit the .bat file in the main folder, but the default folder is on many lines so make sure you edit it in all places. I can see if I can put it in a variable so you have to set it only once.

**Comment by BjornB2** [comment]
[fskneeboard-charts.zip](https://github.com/Christian1984/vfrmap-for-vr/files/8149021/fskneeboard-charts.zip)

In this version you can edit the server location in the top of the click_me_to_prepare.bat file. Make sure there is no trailing \ or any spaces at the end of this line.

**Comment by OverWorldD** [comment]
Thank you!

**Comment by Christian1984** [comment]
done! to be released with v1.9
