### ISSUE TITLE
Minor requests/bugs

### ISSUE THREAD

**Issue by BjornB2** [Christian1984/vfrmap-for-vr#36]
First of all thanks for the great tool. It really works great. 
After using it for a couple of hours I have some minor requests and bugs:

[Request] I would really like the zoom setting (and probably also the other settings in the bottom left) to be saved. Now everytime I have to set the zoom level for VR, which means I keep pressing the + until the toolbar shifts from right to the top. I would not mind setting this in a config file in the server.

[Bug] After adding a waypoint it is no longer possible to pan. You will just add more waypoints. Only minimizing and then maximizing the window (using the - and + in the panel bar) makes panning possible again.

[Bug] Related to the above: If you click a teleport marker thingie there is no way to remove this popup window except from the - + method described above.

[Improvement] When a route is set there often is a rectangle with route info in the way of the view on the map. I had it in front of an airport a couple of times.

[Improvement] When a route is active there is always a pink line between the plane icon and the first waypoint. Could be improved by simply removing this line or by removing waypoints when you get near. The first option would require to set a waypoint at the location of the plane when you click to add a destination.

[Request] The ability to also show .txt files in the cart viewer for flightplan notes etc.

[Improvement] The scratchpad is a nice idea but it's impossible to write with a mouse at the speed ATC is talking. Don't know how this can be improved but currently it's not very useful. I'll try an apple magic touchpad if I can get it to work with my PC.

I will probably come up with more later 😃

**Comment by Christian1984** [comment]
Hey there. A lot to cover :-)

> First of all thanks for the great tool. It really works great. After using it for a couple of hours I have some minor requests and bugs:
> 
> [Request] I would really like the zoom setting (and probably also the other settings in the bottom left) to be saved. Now everytime I have to set the zoom level for VR, which means I keep pressing the + until the toolbar shifts from right to the top. I would not mind setting this in a config file in the server.

Fixed! Will be released with v1.6

> [Bug] After adding a waypoint it is no longer possible to pan. You will just add more waypoints. Only minimizing and then maximizing the window (using the - and + in the panel bar) makes panning possible again.

Question/Verification: Ist this still an issue? Personally, I have never encountered it.

> [Bug] Related to the above: If you click a teleport marker thingie there is no way to remove this popup window except from the - + method described above.

Question/Verification: The popup should disappear as soon as you change back to waypoint mode. Is this still an issue?

> [Improvement] When a route is set there often is a rectangle with route info in the way of the view on the map. I had it in front of an airport a couple of times.

Works for me: Click the corresponding waypoint to show/hide the nav flag (see https://github.com/Christian1984/vfrmap-for-vr/raw/master/screenshots/fskneeboard-map-legend.png)

> [Improvement] When a route is active there is always a pink line between the plane icon and the first waypoint. Could be improved by simply removing this line or by removing waypoints when you get near. The first option would require to set a waypoint at the location of the plane when you click to add a destination.

Works for me: Click the airplane itself to toggle rubberband on/off (see https://github.com/Christian1984/vfrmap-for-vr/raw/master/screenshots/fskneeboard-map-legend.png)

> [Request] The ability to also show .txt files in the cart viewer for flightplan notes etc.

Feature Request: Will put this request in my backlog.

> [Improvement] The scratchpad is a nice idea but it's impossible to write with a mouse at the speed ATC is talking. Don't know how this can be improved but currently it's not very useful. I'll try an apple magic touchpad if I can get it to work with my PC.

Fixed! v1.6 comes with an onscreen keyboard and physical keyboard inputs for taking notes, see https://discord.com/channels/849188204426690562/850776119963287593/941629478407389255 and https://discord.com/channels/849188204426690562/850776119963287593/941686756804272129 for feature preview

> I will probably come up with more later 😃

Looking through my answers above I will close the issue. Please respond to my questions above to reopen. Ideally, please open individual issues for each bullet in question. It is much easier to track and manage this way. For discussion about a feature idea, please also consider joining https://discord.fskneeboard.com to address and discuss issues more "casually" :-)
