### ISSUE TITLE
Feature Request - charts fine rotate feature

### ISSUE THREAD

**Issue by andyanfieldroad** [Christian1984/vfrmap-for-vr#40]
As a VFR real world pilot using MSFS for practice I need to be able to load real world charts into FSKneeboard as image files.  This is easily accomplished since you can often get real world navigation charts to download as pdf files and then export them as a PNG.

However, when flying I need to orient the chart to the track direction and the existing rotate feature only works in steps of 90 degrees.

Is it possible to have the rotate feature work in smaller steps?  Perhaps the easiest approach would be a "fine" and "coarse" toggle button for rotate whereby you can rotate in 10 degree stepsor 90 degree steps.

**Comment by Christian1984** [comment]
done, to be released with v1.9
